[toolchain]
channel = "stable"
profile = "default"
components = ["clippy", "rustfmt", "rust-src"]

targets = [
  "aarch64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "aarch64-pc-windows-msvc",
]
